# Fly.io configuration for User Frontend
# BIID Point App - ユーザーアプリ (Next.js)

app = "biid-user"
primary_region = "nrt"  # Tokyo (Narita)

[build]
  dockerfile = "Dockerfile"
  [build.args]
    NEXT_PUBLIC_GOOGLE_MAPS_API_KEY = "AIzaSyBFw0Qbyq9zTFTd-tUY6dZWTgaQzuU17R8"

[env]
  NODE_ENV = "production"
  NEXT_PUBLIC_API_URL = "https://biid-user-api.fly.dev"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

  [http_service.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

[[vm]]
  memory = "256mb"
  cpu_kind = "shared"
  cpus = 1
