# Fly.io configuration for Store Backend
# BIID Point App - 店舗管理サービス

app = "biid-store"
primary_region = "nrt"  # Tokyo (Narita)

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8002"
  DEBUG = "False"
  USE_POSTGRESQL = "True"
  USE_REDIS = "True"
  STORE_ALLOWED_HOSTS = ".fly.dev,store.biid.app,biid-store.fly.dev"
  SECURE_SSL_REDIRECT = "False"
  SESSION_COOKIE_SECURE = "False"
  CSRF_COOKIE_SECURE = "False"

[[services]]
  internal_port = 8002
  protocol = "tcp"

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  # [[services.tcp_checks]]
  #   interval = "15s"
  #   timeout = "2s"
  #   grace_period = "10s"

  # [[services.http_checks]]
  #   interval = "30s"
  #   timeout = "5s"
  #   grace_period = "10s"
  #   method = "get"
  #   path = "/health/"
  #   protocol = "http"

[mounts]
  source = "store_data"
  destination = "/data"
