# Generated by Django 4.2.23 on 2025-07-09 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('gift_type', models.CharField(choices=[('digital', 'デジタルギフト'), ('coupon', 'クーポン'), ('voucher', 'バウチャー'), ('physical', '現物商品')], default='digital', max_length=20)),
                ('points_required', models.IntegerField()),
                ('original_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('stock_quantity', models.IntegerField(default=0)),
                ('unlimited_stock', models.BooleanField(default=False)),
                ('image_url', models.URLField(blank=True)),
                ('thumbnail_url', models.URLField(blank=True)),
                ('provider_name', models.CharField(max_length=255)),
                ('provider_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('active', '有効'), ('inactive', '無効'), ('sold_out', '売り切れ'), ('discontinued', '販売終了')], default='active', max_length=20)),
                ('available_from', models.DateTimeField(blank=True, null=True)),
                ('available_until', models.DateTimeField(blank=True, null=True)),
                ('usage_instructions', models.TextField(blank=True)),
                ('terms_conditions', models.TextField(blank=True)),
                ('exchange_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GiftCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GiftExchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_spent', models.IntegerField()),
                ('exchange_code', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('pending', '処理中'), ('completed', '完了'), ('failed', '失敗'), ('cancelled', 'キャンセル'), ('expired', '期限切れ')], default='pending', max_length=20)),
                ('delivery_method', models.CharField(blank=True, max_length=50)),
                ('delivery_address', models.TextField(blank=True)),
                ('recipient_name', models.CharField(blank=True, max_length=255)),
                ('recipient_email', models.EmailField(blank=True, max_length=254)),
                ('recipient_phone', models.CharField(blank=True, max_length=20)),
                ('digital_code', models.CharField(blank=True, max_length=500)),
                ('digital_url', models.URLField(blank=True)),
                ('qr_code_url', models.URLField(blank=True)),
                ('exchanged_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('gift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchanges', to='core.gift')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gift_exchanges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-exchanged_at'],
            },
        ),
        migrations.AddField(
            model_name='gift',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gifts', to='core.giftcategory'),
        ),
    ]
