# Generated by Django 4.2.23 on 2025-07-15 08:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_backup_codes_user_is_2fa_enabled_user_role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIAccessKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=40, unique=True)),
                ('partner_name', models.CharField(max_length=255)),
                ('shared_secret', models.CharField(max_length=255)),
                ('hash_algorithm', models.CharField(default='SHA1', max_length=10)),
                ('time_step', models.IntegerField(default=30)),
                ('totp_digits', models.IntegerField(default=6)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('logo_url', models.URLField(blank=True)),
                ('allowed_prices', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='failed_login_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='last_failed_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='suspicious_activity_count',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='PurchaseID',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('prices', models.JSONField(default=list)),
                ('name', models.CharField(max_length=255)),
                ('issuer', models.CharField(max_length=255)),
                ('is_strict', models.BooleanField(default=True)),
                ('color_main', models.CharField(blank=True, max_length=6)),
                ('color_sub', models.CharField(blank=True, max_length=6)),
                ('face_image_url', models.URLField(blank=True)),
                ('header_image_url', models.URLField(blank=True)),
                ('video_url', models.URLField(blank=True)),
                ('video_play_time', models.IntegerField(default=0)),
                ('ad_image_url', models.URLField(blank=True)),
                ('ad_redirect_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('access_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.apiaccesskey')),
                ('brands', models.ManyToManyField(related_name='purchase_ids', to='core.brand')),
            ],
        ),
        migrations.CreateModel(
            name='GiftPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(max_length=40, unique=True)),
                ('gift_code', models.CharField(max_length=50, unique=True)),
                ('gift_url', models.URLField()),
                ('price', models.IntegerField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commission', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('commission_tax', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.CharField(default='JPY', max_length=3)),
                ('status', models.CharField(choices=[('pending', '処理中'), ('completed', '完了'), ('failed', '失敗'), ('expired', '期限切れ')], default='pending', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gift_exchange', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.giftexchange')),
                ('purchase_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.purchaseid')),
            ],
        ),
        migrations.CreateModel(
            name='SecurityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('LOGIN_SUCCESS', 'ログイン成功'), ('LOGIN_FAILURE', 'ログイン失敗'), ('BLOCKED_IP_ACCESS', 'ブロックIPアクセス'), ('RATE_LIMIT_EXCEEDED', 'レート制限超過'), ('ANOMALY_DETECTED', '異常検知'), ('IP_BLOCKED', 'IPブロック'), ('FRAUD_ATTEMPT', '不正試行'), ('ACCOUNT_LOCKED', 'アカウントロック'), ('SUSPICIOUS_ACTIVITY', '不審な活動')], max_length=30)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('request_path', models.CharField(blank=True, max_length=255)),
                ('request_data', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('additional_data', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['event_type', 'timestamp'], name='core_securi_event_t_195db6_idx'), models.Index(fields=['ip_address', 'timestamp'], name='core_securi_ip_addr_7d786f_idx'), models.Index(fields=['user', 'timestamp'], name='core_securi_user_id_9621f9_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('CREATE', '作成'), ('UPDATE', '更新'), ('DELETE', '削除'), ('ACCESS', 'アクセス'), ('EXPORT', 'エクスポート'), ('IMPORT', 'インポート'), ('ADMIN_ACTION', '管理者アクション')], max_length=20)),
                ('object_type', models.CharField(max_length=50)),
                ('object_id', models.CharField(blank=True, max_length=100)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='core_auditl_user_id_7b678c_idx'), models.Index(fields=['action_type', 'timestamp'], name='core_auditl_action__64f4df_idx'), models.Index(fields=['object_type', 'timestamp'], name='core_auditl_object__49c4a9_idx')],
            },
        ),
        migrations.CreateModel(
            name='APIRateLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('request_count', models.IntegerField(default=0)),
                ('window_start', models.DateTimeField()),
                ('access_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.apiaccesskey')),
            ],
            options={
                'unique_together': {('access_key', 'ip_address')},
            },
        ),
    ]
