# Generated by Django 4.2.23 on 2025-07-29 06:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_business_features'),
    ]

    operations = [
        migrations.RunSQL(
            "CREATE TABLE IF NOT EXISTS core_userpoint (id INTEGER PRIMARY KEY AUTOINCREMENT, points INTEGER NOT NULL, expiry_date DATETIME NULL, created_at DATETIME NOT NULL, is_expired BOOLEAN NOT NULL DEFAULT 0, user_id BIGINT NOT NULL REFERENCES core_user(id), source_transaction_id BIGINT NULL REFERENCES core_pointtransaction(id));",
            reverse_sql="DROP TABLE IF EXISTS core_userpoint;"
        ),
        migrations.RunSQL(
            "CREATE TABLE IF NOT EXISTS core_pointtransfer (id INTEGER PRIMARY KEY AUTOINCREMENT, points INTEGER NOT NULL, status VARCHAR(20) NOT NULL DEFAULT 'pending', message TEXT NOT NULL, transfer_fee DECIMAL(10,2) NOT NULL DEFAULT 0, created_at DATETIME NOT NULL, processed_at DATETIME NULL, sender_id BIGINT NOT NULL REFERENCES core_user(id), recipient_id BIGINT NOT NULL REFERENCES core_user(id));",
            reverse_sql="DROP TABLE IF EXISTS core_pointtransfer;"
        ),
        migrations.RunSQL(
            "CREATE TABLE IF NOT EXISTS core_notification (id INTEGER PRIMARY KEY AUTOINCREMENT, notification_type VARCHAR(20) NOT NULL, title VARCHAR(255) NOT NULL, message TEXT NOT NULL, is_read BOOLEAN NOT NULL DEFAULT 0, is_sent BOOLEAN NOT NULL DEFAULT 0, email_sent BOOLEAN NOT NULL DEFAULT 0, created_at DATETIME NOT NULL, read_at DATETIME NULL, user_id BIGINT NOT NULL REFERENCES core_user(id));",
            reverse_sql="DROP TABLE IF EXISTS core_notification;"
        ),
        migrations.RunSQL(
            "CREATE TABLE IF NOT EXISTS core_promotionmail (id INTEGER PRIMARY KEY AUTOINCREMENT, title VARCHAR(255) NOT NULL, content TEXT NOT NULL, target_area VARCHAR(20) NULL, target_user_rank VARCHAR(20) NULL, send_cost DECIMAL(10,2) NOT NULL, recipients_count INTEGER NOT NULL DEFAULT 0, sent_count INTEGER NOT NULL DEFAULT 0, status VARCHAR(20) NOT NULL DEFAULT 'draft', scheduled_at DATETIME NULL, sent_at DATETIME NULL, created_at DATETIME NOT NULL, store_id BIGINT NOT NULL REFERENCES core_store(id));",
            reverse_sql="DROP TABLE IF EXISTS core_promotionmail;"
        ),
        migrations.RunSQL(
            "CREATE TABLE IF NOT EXISTS core_accountrank (id INTEGER PRIMARY KEY AUTOINCREMENT, rank VARCHAR(20) NOT NULL UNIQUE, required_points INTEGER NOT NULL, required_transactions INTEGER NOT NULL DEFAULT 0, point_multiplier DECIMAL(5,2) NOT NULL DEFAULT 1.00, privileges TEXT NOT NULL, created_at DATETIME NOT NULL);",
            reverse_sql="DROP TABLE IF EXISTS core_accountrank;"
        ),
        migrations.RunSQL(
            "CREATE TABLE IF NOT EXISTS core_refundrequest (id INTEGER PRIMARY KEY AUTOINCREMENT, points_to_refund INTEGER NOT NULL, refund_amount DECIMAL(10,2) NOT NULL, refund_type VARCHAR(20) NOT NULL, status VARCHAR(20) NOT NULL DEFAULT 'pending', reason TEXT NOT NULL, bank_name VARCHAR(255) NOT NULL, branch_name VARCHAR(255) NOT NULL, account_type VARCHAR(10) NOT NULL, account_number VARCHAR(20) NOT NULL, account_holder VARCHAR(255) NOT NULL, admin_notes TEXT NOT NULL, processing_fee DECIMAL(10,2) NOT NULL DEFAULT 0, requested_at DATETIME NOT NULL, processed_at DATETIME NULL, completed_at DATETIME NULL, user_id BIGINT NOT NULL REFERENCES core_user(id), processed_by_id BIGINT NULL REFERENCES core_user(id));",
            reverse_sql="DROP TABLE IF EXISTS core_refundrequest;"
        ),
        migrations.RunSQL(
            "CREATE TABLE IF NOT EXISTS core_blogtheme (id INTEGER PRIMARY KEY AUTOINCREMENT, name VARCHAR(255) NOT NULL, description TEXT NOT NULL, primary_color VARCHAR(7) NOT NULL DEFAULT '#ec4899', secondary_color VARCHAR(7) NOT NULL DEFAULT '#f43f5e', accent_color VARCHAR(7) NOT NULL DEFAULT '#8b5cf6', background_color VARCHAR(7) NOT NULL DEFAULT '#fdf2f8', text_color VARCHAR(7) NOT NULL DEFAULT '#1f2937', font_family VARCHAR(255) NOT NULL DEFAULT 'Inter, sans-serif', font_size_base VARCHAR(10) NOT NULL DEFAULT '16px', layout_type VARCHAR(20) NOT NULL DEFAULT 'default', custom_css TEXT NOT NULL, is_active BOOLEAN NOT NULL DEFAULT 1, is_premium BOOLEAN NOT NULL DEFAULT 0, price DECIMAL(10,2) NOT NULL DEFAULT 0, created_at DATETIME NOT NULL);",
            reverse_sql="DROP TABLE IF EXISTS core_blogtheme;"
        ),
        migrations.RunSQL(
            "CREATE TABLE IF NOT EXISTS core_userblogtheme (id INTEGER PRIMARY KEY AUTOINCREMENT, purchased_at DATETIME NOT NULL, user_id BIGINT NOT NULL UNIQUE REFERENCES core_user(id), theme_id BIGINT NOT NULL REFERENCES core_blogtheme(id));",
            reverse_sql="DROP TABLE IF EXISTS core_userblogtheme;"
        ),
        # Add new fields to existing tables
        migrations.RunSQL(
            "ALTER TABLE core_user ADD COLUMN rank VARCHAR(20) DEFAULT 'bronze';",
            reverse_sql="ALTER TABLE core_user DROP COLUMN rank;"
        ),
        migrations.RunSQL(
            "ALTER TABLE core_store ADD COLUMN area VARCHAR(20) NULL;",
            reverse_sql="ALTER TABLE core_store DROP COLUMN area;"
        ),
        migrations.RunSQL(
            "ALTER TABLE core_store ADD COLUMN deposit_balance DECIMAL(10,2) DEFAULT 0;",
            reverse_sql="ALTER TABLE core_store DROP COLUMN deposit_balance;"
        ),
        migrations.RunSQL(
            "ALTER TABLE core_store ADD COLUMN deposit_auto_charge BOOLEAN DEFAULT 0;",
            reverse_sql="ALTER TABLE core_store DROP COLUMN deposit_auto_charge;"
        ),
        migrations.RunSQL(
            "ALTER TABLE core_store ADD COLUMN deposit_auto_charge_amount DECIMAL(10,2) DEFAULT 0;",
            reverse_sql="ALTER TABLE core_store DROP COLUMN deposit_auto_charge_amount;"
        ),
        migrations.RunSQL(
            "ALTER TABLE core_pointtransaction ADD COLUMN refund_rate DECIMAL(5,2) DEFAULT 100.00;",
            reverse_sql="ALTER TABLE core_pointtransaction DROP COLUMN refund_rate;"
        ),
        migrations.RunSQL(
            "ALTER TABLE core_pointtransaction ADD COLUMN refund_fee DECIMAL(10,2) DEFAULT 0;",
            reverse_sql="ALTER TABLE core_pointtransaction DROP COLUMN refund_fee;"
        ),
    ]
