# Generated by Django 4.2.23 on 2025-07-29 06:20

from django.db import migrations, models
import django.db.models.deletion


def create_initial_areas(apps, schema_editor):
    """初期エリアデータを作成"""
    Area = apps.get_model('core', 'Area')
    initial_areas = [
        {'name': '北新地', 'display_order': 1},
        {'name': 'ミナミ', 'display_order': 2},
        {'name': '渋谷', 'display_order': 3},
        {'name': '銀座', 'display_order': 4},
        {'name': '表参道', 'display_order': 5},
    ]
    
    for area_data in initial_areas:
        Area.objects.get_or_create(
            name=area_data['name'],
            defaults={'display_order': area_data['display_order']}
        )


def reverse_create_initial_areas(apps, schema_editor):
    """逆マイグレーション - 初期エリアデータを削除"""
    Area = apps.get_model('core', 'Area')
    initial_area_names = ['北新地', 'ミナミ', '渋谷', '銀座', '表参道']
    Area.objects.filter(name__in=initial_area_names).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_new_business_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'エリア',
                'verbose_name_plural': 'エリア',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.RunPython(create_initial_areas, reverse_create_initial_areas),
        migrations.AlterField(
            model_name='promotionmail',
            name='target_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotion_mails', to='core.area'),
        ),
        migrations.AlterField(
            model_name='store',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stores', to='core.area'),
        ),
    ]
