# Generated by Django 4.2.23 on 2025-07-31 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_melty_integration'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='selected_social_skin',
            field=models.CharField(
                blank=True,
                choices=[('classic', 'Classic'), ('modern', 'Modern'), ('casual', 'Casual')],
                help_text="User's selected social profile theme",
                max_length=20,
                null=True
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='unlocked_social_skins',
            field=models.JSONField(
                default=lambda: ['classic', 'modern', 'casual'],
                help_text='List of unlocked social skin themes'
            ),
        ),
    ]
