# Generated by Django 4.2.23 on 2025-07-29 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_email_notification_system'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('transaction_type', models.CharField(choices=[('charge', 'チャージ'), ('consumption', '消費'), ('refund', '返金'), ('auto_charge', '自動チャージ'), ('bonus', 'ボーナス'), ('penalty', 'ペナルティ')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance_before', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(blank=True, choices=[('credit_card', 'クレジットカード'), ('bank_transfer', '銀行振込'), ('convenience_store', 'コンビニ決済'), ('digital_wallet', 'デジタルウォレット'), ('system', 'システム処理')], max_length=20, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', '処理中'), ('completed', '完了'), ('failed', '失敗'), ('cancelled', 'キャンセル'), ('refunded', '返金済み')], default='pending', max_length=20)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('fee_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fee_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('related_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.deposittransaction')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposit_transactions', to='core.store')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DepositUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_for', models.CharField(help_text='使用目的（プロモーション、広告費など）', max_length=100)),
                ('used_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user_count', models.IntegerField(default=0, help_text='対象ユーザー数')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_promotion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.promotionmail')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposit_usage_logs', to='core.store')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='core.deposittransaction')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DepositAutoChargeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False)),
                ('trigger_amount', models.DecimalField(decimal_places=2, help_text='この金額を下回ったら自動チャージ', max_digits=10)),
                ('charge_amount', models.DecimalField(decimal_places=2, help_text='チャージする金額', max_digits=10)),
                ('payment_method', models.CharField(choices=[('credit_card', 'クレジットカード'), ('bank_transfer', '銀行振込'), ('convenience_store', 'コンビニ決済'), ('digital_wallet', 'デジタルウォレット'), ('system', 'システム処理')], max_length=20)),
                ('payment_reference', models.CharField(blank=True, help_text='カード番号（下4桁）など', max_length=255)),
                ('max_charge_per_day', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_charge_per_month', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notification_enabled', models.BooleanField(default=True)),
                ('notification_email', models.EmailField(blank=True, max_length=254)),
                ('last_triggered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auto_charge_rule', to='core.store')),
            ],
        ),
        migrations.AddIndex(
            model_name='deposittransaction',
            index=models.Index(fields=['store', 'created_at'], name='core_deposi_store_i_ecbe31_idx'),
        ),
        migrations.AddIndex(
            model_name='deposittransaction',
            index=models.Index(fields=['transaction_type', 'status'], name='core_deposi_transac_9bd611_idx'),
        ),
        migrations.AddIndex(
            model_name='deposittransaction',
            index=models.Index(fields=['status', 'created_at'], name='core_deposi_status_7bdb24_idx'),
        ),
    ]
