# Generated by Django 5.2.7 on 2025-11-01 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_create_industry_master'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicearea',
            options={'ordering': ['area_code'], 'verbose_name': 'サービスエリア', 'verbose_name_plural': 'サービスエリア'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='melty_linked_at',
        ),
        migrations.AddField(
            model_name='gift',
            name='external_brand',
            field=models.ForeignKey(blank=True, help_text='連携するデジタルギフトブランド', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gifts', to='core.digitalgiftbrand'),
        ),
        migrations.AddField(
            model_name='gift',
            name='external_price',
            field=models.IntegerField(blank=True, help_text='外部API購入金額(円)', null=True),
        ),
        migrations.AddField(
            model_name='gift',
            name='is_external_gift',
            field=models.BooleanField(default=False, help_text='RealPay等の外部デジタルギフトAPI経由か'),
        ),
        migrations.AlterField(
            model_name='industry',
            name='category',
            field=models.CharField(blank=True, help_text='カテゴリ (例: nightwork)', max_length=100),
        ),
        migrations.AlterField(
            model_name='industry',
            name='code',
            field=models.CharField(help_text='業種コード (例: nightwork_cabaret)', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='industry',
            name='name',
            field=models.CharField(help_text='表示名 (例: ナイトワーク(キャバクラ・クラブ等))', max_length=200),
        ),
        migrations.AlterField(
            model_name='servicearea',
            name='area_code',
            field=models.CharField(help_text='エリアコード（例: minami, kitashinchi）', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='servicearea',
            name='area_name',
            field=models.CharField(help_text='エリア名（日本語）', max_length=100),
        ),
        migrations.AlterField(
            model_name='servicearea',
            name='area_name_en',
            field=models.CharField(blank=True, default='', help_text='エリア名（英語）', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servicearea',
            name='boundary_east',
            field=models.DecimalField(decimal_places=7, help_text='東端の経度', max_digits=10),
        ),
        migrations.AlterField(
            model_name='servicearea',
            name='boundary_north',
            field=models.DecimalField(decimal_places=7, help_text='北端の緯度', max_digits=10),
        ),
        migrations.AlterField(
            model_name='servicearea',
            name='boundary_south',
            field=models.DecimalField(decimal_places=7, help_text='南端の緯度', max_digits=10),
        ),
        migrations.AlterField(
            model_name='servicearea',
            name='boundary_west',
            field=models.DecimalField(decimal_places=7, help_text='西端の経度', max_digits=10),
        ),
        migrations.AlterField(
            model_name='servicearea',
            name='center_latitude',
            field=models.DecimalField(decimal_places=7, help_text='中心の緯度', max_digits=10),
        ),
        migrations.AlterField(
            model_name='servicearea',
            name='center_longitude',
            field=models.DecimalField(decimal_places=7, help_text='中心の経度', max_digits=10),
        ),
        migrations.AlterField(
            model_name='servicearea',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='servicearea',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='servicearea',
            name='is_active',
            field=models.BooleanField(default=True, help_text='このエリアが有効かどうか'),
        ),
        migrations.AlterField(
            model_name='servicearea',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='area_code',
            field=models.CharField(blank=True, default='', help_text='エリアコード', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='store',
            name='city',
            field=models.CharField(blank=True, help_text='市区町村', max_length=100),
        ),
        migrations.AlterField(
            model_name='store',
            name='district',
            field=models.CharField(blank=True, default='', help_text='地区名', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='store',
            name='is_area_verified',
            field=models.BooleanField(default=False, help_text='エリア検証済みフラグ'),
        ),
        migrations.AlterField(
            model_name='store',
            name='prefecture',
            field=models.CharField(blank=True, help_text='都道府県', max_length=50),
        ),
        migrations.AlterField(
            model_name='store',
            name='service_area',
            field=models.ForeignKey(blank=True, help_text='サービス提供エリア（ミナミ、北新地等）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='area_stores', to='core.servicearea'),
        ),
        migrations.AlterField(
            model_name='user',
            name='employment_type',
            field=models.CharField(blank=True, choices=[('専業', '専業'), ('副業', '副業')], help_text='働き方', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='industry',
            field=models.CharField(blank=True, help_text='業種 (11選択肢)', max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='work_region',
            field=models.CharField(blank=True, help_text='勤務地域 (47都道府県)', max_length=100),
        ),
    ]
