# Generated by Django 4.2.23 on 2025-07-29 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_accountrank_pointtransfer_notification_and_more'),
        ('core', '0004_apiaccesskey_brand_user_failed_login_attempts_and_more'),
        ('core', '0007_deposittransaction_depositusagelog_and_more'),
    ]

    operations = [
    ]
