# Generated by Django 4.2 on 2025-11-07 01:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_servicearea_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ECPointRequestMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='メッセージ本文')),
                ('is_from_store', models.BooleanField(default=False, verbose_name='店舗からの送信')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='送信日時')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.ecpointrequest', verbose_name='EC申請')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='送信者')),
            ],
            options={
                'verbose_name': 'ECポイント申請メッセージ',
                'verbose_name_plural': 'ECポイント申請メッセージ',
                'db_table': 'ec_point_request_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='ecpointrequestmessage',
            index=models.Index(fields=['request', 'created_at'], name='ec_point_re_request_f41039_idx'),
        ),
    ]
