# Generated by Django 4.2.23 on 2025-07-29 08:57

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_merge_20250729_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointPurchaseTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=40, unique=True)),
                ('points_amount', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, default=1.08, max_digits=10)),
                ('subtotal', models.IntegerField()),
                ('tax', models.IntegerField()),
                ('total_amount', models.IntegerField()),
                ('payment_method', models.CharField(choices=[('credit_card', 'クレジットカード'), ('deposit', 'デポジット')], max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', '処理中'), ('success', '成功'), ('failed_card', 'カード決済失敗'), ('failed_deposit', 'デポジット不足'), ('refunded', '返金済み')], default='pending', max_length=20)),
                ('card_payment_id', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_purchases', to='core.store')),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_purchases_received', to=settings.AUTH_USER_MODEL)),
                ('deposit_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.deposittransaction')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyBilling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_id', models.CharField(max_length=40, unique=True)),
                ('billing_year', models.IntegerField()),
                ('billing_month', models.IntegerField()),
                ('billing_period_start', models.DateField()),
                ('billing_period_end', models.DateField()),
                ('total_points_purchased', models.IntegerField(default=0)),
                ('subtotal', models.IntegerField(default=0)),
                ('tax', models.IntegerField(default=0)),
                ('total_amount', models.IntegerField(default=0)),
                ('deposit_used', models.IntegerField(default=0)),
                ('credit_charged', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', '下書き'), ('finalized', '確定'), ('sent', '送信済み'), ('paid', '支払い済み'), ('overdue', '延滞'), ('cancelled', 'キャンセル')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('invoice_pdf_path', models.CharField(blank=True, max_length=500)),
                ('notes', models.TextField(blank=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_billings', to='core.store')),
            ],
            options={
                'ordering': ['-billing_year', '-billing_month'],
            },
        ),
        migrations.AddField(
            model_name='pointpurchasetransaction',
            name='monthly_billing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.monthlybilling'),
        ),
        migrations.AddIndex(
            model_name='pointpurchasetransaction',
            index=models.Index(fields=['store', 'payment_status'], name='core_pointp_store_i_b9f2c9_idx'),
        ),
        migrations.AddIndex(
            model_name='pointpurchasetransaction',
            index=models.Index(fields=['target_user', 'created_at'], name='core_pointp_target__582a73_idx'),
        ),
        migrations.AddIndex(
            model_name='pointpurchasetransaction',
            index=models.Index(fields=['transaction_id'], name='core_pointp_transac_a6f72e_idx'),
        ),
        migrations.AddIndex(
            model_name='pointpurchasetransaction',
            index=models.Index(fields=['monthly_billing'], name='core_pointp_monthly_cb8a45_idx'),
        ),
        migrations.AddIndex(
            model_name='monthlybilling',
            index=models.Index(fields=['store', 'billing_year', 'billing_month'], name='core_monthl_store_i_8ccb39_idx'),
        ),
        migrations.AddIndex(
            model_name='monthlybilling',
            index=models.Index(fields=['status', 'due_date'], name='core_monthl_status_b46fa3_idx'),
        ),
        migrations.AddIndex(
            model_name='monthlybilling',
            index=models.Index(fields=['billing_id'], name='core_monthl_billing_0b12f0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='monthlybilling',
            unique_together={('store', 'billing_year', 'billing_month')},
        ),
    ]
