# Generated by Django 5.2.5 on 2025-12-09 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_add_ec_request_message_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verification_code',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verification_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
